apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: kube-system
  labels:
    app: ingress-nginx

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: kube-system

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: kube-system
