apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: default-http-backend
  labels:
    k8s-app: default-http-backend
    version: "__KUBE_DEFAULTBACKEND_VERSION__"
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: default-http-backend
      version: "__KUBE_DEFAULTBACKEND_VERSION__"
  template:
    metadata:
      labels:
        k8s-app: default-http-backend
        version: "__KUBE_DEFAULTBACKEND_VERSION__"
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend
        # Any image is permissible as long as:
        # 1. It serves a 404 page at /
        # 2. It serves 200 on a /healthz endpoint
        image: __KUBE_DEFAULTBACKEND_IMAGE__
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi

---

apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  namespace: kube-system
  labels:
    k8s-app: default-http-backend
    version: "__KUBE_DEFAULTBACKEND_VERSION__"
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    k8s-app: default-http-backend
    version: "__KUBE_DEFAULTBACKEND_VERSION__"
