apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
    name: heapster
    version: canary
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: canary
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: canary
    spec:
      containers:
      - name: heapster
        image: 10.1.1.16:5000/gcr.io/heapster:canary
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes:http://10.1.1.16:8080?inClusterConfig=false
        - --sink=influxdb:http://monitoring-influxdb:8086
