apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: heapster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:heapster
subjects:
- kind: ServiceAccount
  name: heapster
  namespace: kube-system

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: heapster
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: heapster-config
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  NannyConfiguration: |-
    apiVersion: nannyconfig/v1alpha1
    kind: NannyConfiguration

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: eventer-config
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  NannyConfiguration: |-
    apiVersion: nannyconfig/v1alpha1
    kind: NannyConfiguration

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: "__KUBE_HEAPSTER_VERSION__"
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: heapster
      version: "__KUBE_HEAPSTER_VERSION__"
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: "__KUBE_HEAPSTER_VERSION__"
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: __KUBE_HEAPSTER_IMAGE__
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 180
          timeoutSeconds: 5
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:http://influxdb:8086
      - image: __KUBE_HEAPSTER_IMAGE__
        name: eventer
        command:
        - /eventer
        - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:http://influxdb:8086
      - image: __KUBE_ADDON_RESIZER_IMAGE__
        name: heapster-nanny
        resources:
          limits:
            cpu: 50m
            memory: __nanny_memory__
          requests:
            cpu: 50m
            memory: __nanny_memory__
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
        - /pod_nanny
        - --config-dir=/etc/config
        - --cpu=__base_metrics_cpu__
        - --extra-cpu=__metrics_memory_per_node__m
        - --memory=__base_metrics_memory__
        - --extra-memory=__metrics_memory_per_node__Mi
        - --threshold=5
        - --deployment=heapster
        - --container=heapster
        - --poll-period=300000
        - --estimator=exponential
        volumeMounts:
        - name: heapster-config-volume
          mountPath: /etc/config
      - image: __KUBE_ADDON_RESIZER_IMAGE__
        name: eventer-nanny
        resources:
          limits:
            cpu: 50m
            memory: __nanny_memory__
          requests:
            cpu: 50m
            memory: __nanny_memory__
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
        - /pod_nanny
        - --config-dir=/etc/config
        - --cpu=100m
        - --extra-cpu=0m
        - --memory=__base_eventer_memory__
        - --extra-memory=__eventer_memory_per_node__Ki
        - --threshold=5
        - --deployment=heapster
        - --container=eventer
        - --poll-period=300000
        - --estimator=exponential
        volumeMounts:
        - name: eventer-config-volume
          mountPath: /etc/config
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      volumes:
      - name: heapster-config-volume
        configMap:
          name: heapster-config
      - name: eventer-config-volume
        configMap:
          name: eventer-config

---

apiVersion: v1
kind: Service
metadata:
  name: heapster
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: "__KUBE_HEAPSTER_VERSION__"
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Heapster"
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    k8s-app: heapster
    version: "__KUBE_HEAPSTER_VERSION__"
